In [22]:
#https://www.cnblogs.com/sparkwen/p/3155850.html
import numpy as np

In [23]:
A = np.array([[2, -1, -1, 0, 0, 0, 0],
              [-1, 3, -1, -1, 0, 0, 0],
              [-1, -1, 2, 0, 0, 0, 0],
              [0, -1, 0, 4, -1, -1, -1],
              [0, 0, 0, -1, 2, -1, 0],
              [0, 0, 0, -1, -1, 3, -1],
              [0, 0, 0, -1, 0, -1, 2]])

In [24]:
a, b = np.linalg.eig(A)

In [25]:
a

array([-5.55111512e-17,  3.98320868e-01,  5.26180225e+00,  3.00000000e+00,
        3.33987689e+00,  4.00000000e+00,  2.00000000e+00])

In [26]:
# 第一列对应第一个特征值，第二列对应第二个特征值
b

array([[-3.77964473e-01, -4.92886500e-01, -1.06502348e-01,
         7.07106781e-01, -3.20722630e-01, -1.43455444e-16,
         5.23723739e-17],
       [-3.77964473e-01, -2.96559521e-01,  4.53891948e-01,
         1.92325595e-15,  7.50451469e-01,  9.53765695e-16,
         1.38176852e-16],
       [-3.77964473e-01, -4.92886500e-01, -1.06502348e-01,
        -7.07106781e-01, -3.20722630e-01, -6.66854807e-16,
        -1.38176852e-16],
       [-3.77964473e-01,  2.14220282e-01, -8.13609130e-01,
         6.53077047e-16,  3.86384151e-01,  3.79943919e-16,
         3.34321038e-17],
       [-3.77964473e-01,  3.56037413e-01,  1.90907293e-01,
        -2.72691716e-16, -1.65130120e-01,  4.08248290e-01,
        -7.07106781e-01],
       [-3.77964473e-01,  3.56037413e-01,  1.90907293e-01,
        -3.44096593e-16, -1.65130120e-01, -8.16496581e-01,
        -2.58355914e-17],
       [-3.77964473e-01,  3.56037413e-01,  1.90907293e-01,
        -3.44096593e-16, -1.65130120e-01,  4.08248290e-01,
         7.0710678

In [27]:
np.linalg.eigvals(A)

array([-5.55111512e-17,  3.98320868e-01,  5.26180225e+00,  3.00000000e+00,
        3.33987689e+00,  4.00000000e+00,  2.00000000e+00])